name: Nightly AI

on:
  schedule:
    - cron: '40 1 * * *'
    - cron: '40 6 * * *'
  workflow_dispatch:

jobs:
  run-ai:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: node nightly.js
